apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: polinchw/demo:2.0.0
        name: demo
        resources: 
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 20m
            memory: 50Mi