apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-grallvm-deployment
  name: demo-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: polinchw/dev-11
        name: demo