apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: polinchw/demo:2.1.3
        name: demo
        resources: 
          limits:
            cpu: 150m
            memory: 750Mi
          requests:
            cpu: 150m
            memory: 750Mi
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/demo
          - name: SPRING_DATASOURCE_USERNAME
            value: demo
          - name: SPRING_DATASOURCE_PASSWORD
            value: demo